### ISSUE TITLE
question about heaptrack roslaunched node

### ISSUE THREAD

**Issue by DingFeng9313** [facontidavide/CPP_Optimizations_Diary#15]
I am trying to use heaptrack to track memory. But how to heaptrack roslaunched executable?

I tried:
 heaptrack roslaunch ${pkg_name} ${type_name}

then I found it is heaptracking a python executable "roslaunch" instead of my real executable.

**Comment by facontidavide** [comment]
you need to:

- use the **launch-prefix** http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB
- file will be in the hidden folder **~/.ros/**

**Comment by DingFeng9313** [comment]
thanks a million!
