### ISSUE TITLE
Small vectors - std::array?

### ISSUE THREAD

**Issue by peci1** [facontidavide/CPP_Optimizations_Diary#23]
Hi Davide, thanks for your excellent writeups!

I was just reading the small vector document, and all the time I was thinking: "He's gonna reveal std::array". But you did not. Have I misunderstood something, or is std::array really a "standard solution" to your StaticVector class?

https://github.com/facontidavide/CPP_Optimizations_Diary/blob/e6cca7761dd0a792345d00fdcefee88f7c6920ee/docs/small_vectors.md?plain=1#L107

**Comment by facontidavide** [comment]
It is not the same.

Array has a fixed size. These other non standard alternatives have variable size

**Comment by peci1** [comment]
Ah, right, your implementation supports adding/removing elements up to N items. Good. But I still think std::array could be mentioned on this page, maybe just as a safer alternative to plain C array + size.
