### ISSUE TITLE
Additional recommendations

### ISSUE THREAD

**Issue by SteveMacenski** [facontidavide/CPP_Optimizations_Diary#3]
- talking about how amazing vector caching is. I've often been able to get major improvements in speed when just doing something simple like changing an unordered_map to a vector and playing indexing games even with large data. All depends on your L1 cache size.
- Not allocating variables in loops, preallocate any intermediate variables and just assign them in the loop for use. References encouraged when possible. 
- While strings are heavy... by god do I never want to go back to the days of using anything else
- Release builds.. I cannot tell you the number of times I've had people complain about performance only to find out they were using debug builds on their **production** assets.

**Comment by facontidavide** [comment]
> While strings are heavy... by god do I never want to go back to the days of using anything else

I agree. It is basically a clickbait to go deeper about the fact that **string_view** are a very good tool to use and that pass by reference is important for strings too

> Release builds.. I cannot tell you the number of times I've had people complain about performance only to find out they were using debug builds on their production assets.

Don't tell me about it. 

I will incrementally add suggestions like this to the repository... just need time !

Thanks

**Comment by SteveMacenski** [comment]
About 2 years ago I went on a C++ optimization blog / paper binge. I really only pull those tools out of the tool chest when working with things running at 100hz+ or touching >> 1,000 pieces of memory / iterations since those are where you can get some real improvements from.

I was working on an A* planner and from an optimized version, I was able to get a 10x speed up just modifying small things like data structures and ensuring that you only do memory lookups once an iteration. There's lots of good resources on this topic, people just need to care enough to look into them :wink: Always good to add more with projects like this. 

PS Someone posted this on the navigation2 slack group (navigation2.slack.com) you're welcome to stop on by.

**Comment by facontidavide** [comment]
What you mentioned is exactly the reason you must measure first. Sometimes people try to optimize something that has a negligible impact.

I also had fun optimizing an A*, it is the way I learnt about this data structure

http://www.cplusplus.com/reference/queue/priority_queue/

that is not so well known ;)

**Comment by SteveMacenski** [comment]
Pretty well known in my circles :wink: Its the only way in my mind to do clean heuristic search and helps with robot scheduler tasks. 

https://github.com/SteveMacenski/navigation2/blob/nav2_smac_planner/smac_planner/include/smac_planner/types.hpp#L50

**Comment by facontidavide** [comment]
Solved -- I guess ;)
